name: Verify CHANGELOG

on:
  pull_request:

permissions:
  contents: read

jobs:
  verify-changelog:
    uses: SchoutenEnZn/org-workflows/.github/workflows/verify-changelog.yml@main
    with:
      base_ref: ${{ github.base_ref }}
    secrets: inherit
